Repository CMU-313/fall23-nodebb-jasta, pull requests merged in 2023-10, with the labels that each got.

#47 Anonymous posts test
  test/posts.js
Labels: Tests

#46 Added testing to default email system and updated UserGuide.md
  UserGuide.md
  test/emailer.js
Labels: Tests

#48 User guide for anonymous posts
  UserGuide.md
Labels: documentation

#50 Update user guide to account for failed tests
  UserGuide.md
Labels: documentation

#55 Successfully installed and ran complexity-report static analysis tool
  .complexrc
  coverage_tracked/coverage.md
  package.json
Labels: Small (4 hours), Tests

#52 Installed Static Analysis Tool Flow
  .babelrc
  .gitignore
  package.json
  src/cli/index.js
Labels: Tests
